### ISSUE TITLE
How can i know the file's uid/gid in the ext4img

### ISSUE THREAD

**Issue by Laurie-Lin** [cubinator/ext4#10]
Hi bro,I always use this project to build message for make_ext4fs,After reading this code for a long time i still don't know how to get file uid/gid,some help,thanks

**Comment by cubinator** [comment]
If `inode` is your `ext4.Inode` object, then you get its UID and GID with `inode.inode.i_uid` and `inode.inode.i_gid` respectively.

The `ext4.Inode` class is a wrapper around the on-disk `ext4.ext4_inode` structure, which you can access via the `inode` property of `ext4.Inode`. Keep in mind that I renamed some of the fields of the [original `ext4_inode` structure](https://www.kernel.org/doc/html/latest/filesystems/ext4/inodes.html) in order to enable automatic merging of hi/lo-fields.

|                    | My `ext4` module     | Original ext4_inode            |
|--------------------|----------------------|--------------------------------|
| UID                | Inode.inode.i_uid    |                                |
| UID (Low 16 bits)  | Inode.inode.i_uid_lo | ext4_inode.i_uid               |
| UID (High 16 bits) | Inode.inode.i_uid_hi | ext4_inode.i_osd2.l_i_uid_high |
| GID                | Inode.inode.i_gid    |                                |
| GID (Low 16 bits)  | Inode.inode.i_gid_lo | ext4_inode.i_gid               |
| GID (High 16 bits) | Inode.inode.i_gid_hi | ext4_inode.i_osd2.l_i_gid_high |

**Comment by Laurie-Lin** [comment]
thanks so much,I have no problem now,thanks again,this is very good project
