### ISSUE TITLE
New strange ext4 img files

### ISSUE THREAD

**Issue by superr** [cubinator/ext4#5]
Hello again :)

[Here is a link](http://sr-code.com/cubinator/filemanager.php?file=more_ext4_test_files.zip) to the system.img and vendor.img this issue refers to.

system.img:
I am not sure what is going on here. The bulk of the files are in root/system which I think is inode 20. When listing the files/directories in inode 20 the list is very incomplete compared to the mounted img. When I run my extract script I get strange files in strange places. Some files end up as directories, and not everything is extracted. This is the same extract script I have been using for all other ext4 img files successfully.

vendor.img:
The files/directories seem to extract properly from this one, but my extract script just keeps looping forever, presumably writing the files over and over again. The loop I am using comes from [here](https://github.com/cubinator/ext4/issues/1#issuecomment-362700317).

Both of these img files are from the new developer preview of Android P and just came out. They are the only img files I am having issues with. I hope you can see what is going on. 

Thank you for your time :)

**Comment by cubinator** [comment]
I actually have no clue what's wrong with those files... They mount perfectly fine, but my script and `debugfs`+`stat` disagree on the extent values (pointers from inode to inode's content). As usual I looked into the extent values of some inode (in this case /bin) with a hex editor just to see that my script does everything correct according to documentation, so I think your images might be some variant of ext4 that I don't know of or they use features which I don't know yet (because they are nowhere documented).

**Comment by superr** [comment]
Thank you for looking into it. Out of curiosity I tried extracting with sysXtract and it extracts them both without issue. I suppose it is not obvious how to fix this, but do you have any ideas?

EDIT: p7zip Version 16.02 also reads these files correctly.

**Comment by cubinator** [comment]
I might be onto something: In your images `superblock.s_desc_size` (Byte size of group descriptors) is set to 0 causing [this line](https://github.com/cubinator/ext4/blob/master/ext4.py#L475) to always compute the offset to the first group descriptor instead of the n-th group descriptor. This is related to the 32/64-bit issue from before.
In addition to that I found out why my script refuses to believe that /bin (in vendor.img) is a directory: My script checks whether the `S_IFDIR` flag is set in `ext4_inode.i_mode` (which marks an inode as directory), but in the image `INCOMPAT_FILETYPE` is set in `ext4_superblock.s_feature_incompat`, which means that only the directory referring to an inode controls whether or not the referred inode is a directory or a file.
Let's see whether fixing these things fixes your problem.

**Comment by superr** [comment]
Thank you for working on this! It is only a matter of time before you get it all working perfectly. I am ready and willing to test :)

**Comment by cubinator** [comment]
Just uploaded a newer version of my module. Now it should be fine with `INCOMPAT_64BIT` not being set as is in your case. When calling `Volume.get_inode` while `(volume.superblock.s_feature_incompat & ext4_superblock.INCOMPAT_FILETYPE) != 0`, you have to pass the directory entry's `file_type` as well, so the script you linked above now looks like this

    volume = ext4.Volume(image_file)

    def scan_dir (root_inode, root_path = ""):
        for entry_name, entry_inode_idx, entry_type in root_inode.open_dir():
            if entry_name == "." or entry_name == "..":
                continue # Ignore "." and ".." directories

            entry_inode = root_inode.volume.get_inode(entry_inode_idx, entry_type) # ADDED entry_type parameter
            entry_inode_path = root_path + "/" + entry_name # Remember path

            if entry_inode.is_dir:
                # Things to do for directories only
                print("DIR: {0:s}".format(entry_inode_path))
                scan_dir(entry_inode, entry_inode_path)
            else:
                # Things to do for files only
                print("FILE: {0:s}".format(entry_inode_path))

            # Things to do for both

    scan_dir(volume.root)
    # image_file.close()

Keep in mind though that I only worked with vendor.img so far. It might be the same issue for system.img, but I haven't checked thoroughly yet.

**Comment by superr** [comment]
Flawless :) It works perfect for system.img and vendor.img now. I really can't thank you enough for all your work and time :)
